### ISSUE TITLE
New release (0.3.0?)

### ISSUE THREAD

**Issue by orhun** [poccariswet/apng#27]
There is quite a few changes since the last release:

https://github.com/poccariswet/apng/compare/v0.2.0..master

 I think it would be nice to release a new version of `apng`, preferably `0.3.0`.

I would like to coordinate/push this release since I'm a member of this repository now. (Thanks for the invite BTW!)

@poccariswet what do you think?

**Comment by poccariswet** [comment]
Sorry I'm late in responding...
Let's release it! And orhun you may release, merge PRs, etc. at your discretion.
Thank you for thinking of this repository.

**Comment by orhun** [comment]
Hey @poccariswet! I just released `v0.3.0`: https://github.com/poccariswet/apng/releases/tag/v0.3.0 🚀

Can you update the [crates.io](https://crates.io/crates/apng) release by running `cargo publish`?

Or you can add me to the package as owner, my profile is https://crates.io/users/orhun

**Comment by poccariswet** [comment]
Hi, @orhun 
I have invited you as an owner on crates.io Did you receive my email?:eyes:

**Comment by orhun** [comment]
Yup, `0.3.0` is now published on [crates.io](https://crates.io/crates/apng)

Thank you so much! I think now we can close this issue.
